# Generated by Django 4.1.7 on 2023-04-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='toipc_name',
            new_name='topic_name',
        ),
        migrations.RenameField(
            model_name='webpages',
            old_name='Topic_name',
            new_name='topic_name',
        ),
    ]
